import type { Metadata } from "next";
import { Erica_One, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import InvertCursor from "@/components/InvertCursor";
import Footer from "@/components/Footer";

const ericaOne = Erica_One({
  weight: "400",
  variable: "--font-erica-one",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${ericaOne.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <InvertCursor />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
